export type PaymentMethodPreset = {
  key: string;
  provider: string;
  category: "Pakistan" | "India" | "International" | "Crypto" | "Custom";
  label: string;
  bankName: string;
  logoPath: string;
  accountTitlePlaceholder: string;
  accountNumberLabel: string;
  accountNumberPlaceholder: string;
  instructionsHint: string;
  defaultSupportsDeposit: boolean;
  defaultSupportsWithdrawal: boolean;
};

export const PAYMENT_METHOD_PRESETS: PaymentMethodPreset[] = [
  {
    key: "jazzcash",
    provider: "jazzcash",
    category: "Pakistan",
    label: "JazzCash",
    bankName: "JazzCash",
    logoPath: "/payment-method-logos/presets/jazzcash.svg",
    accountTitlePlaceholder: "JazzCash account title",
    accountNumberLabel: "JazzCash Number",
    accountNumberPlaceholder: "0300 1234567",
    instructionsHint: "Tell the player to send funds through JazzCash and upload the receipt screenshot.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "easypaisa",
    provider: "easypaisa",
    category: "Pakistan",
    label: "EasyPaisa",
    bankName: "EasyPaisa",
    logoPath: "/payment-method-logos/presets/easypaisa.svg",
    accountTitlePlaceholder: "EasyPaisa account title",
    accountNumberLabel: "EasyPaisa Number",
    accountNumberPlaceholder: "03XX XXXXXXX",
    instructionsHint: "Explain the EasyPaisa transfer steps and what proof the player must upload.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "nayapay",
    provider: "nayapay",
    category: "Pakistan",
    label: "NayaPay",
    bankName: "NayaPay",
    logoPath: "/payment-method-logos/presets/nayapay.svg",
    accountTitlePlaceholder: "NayaPay account title",
    accountNumberLabel: "NayaPay Number",
    accountNumberPlaceholder: "03XX XXXXXXX",
    instructionsHint: "Use this for NayaPay transfers and clearly specify receipt requirements.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "ubl",
    provider: "ubl",
    category: "Pakistan",
    label: "UBL Bank",
    bankName: "UBL",
    logoPath: "/payment-method-logos/presets/ubl.svg",
    accountTitlePlaceholder: "UBL account title",
    accountNumberLabel: "Account / IBAN",
    accountNumberPlaceholder: "PK00 UBLX 0000 1234 5678",
    instructionsHint: "Use for UBL bank transfer rails. Mention transfer notes and proof requirements.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "meezan_bank",
    provider: "meezan_bank",
    category: "Pakistan",
    label: "Meezan Bank",
    bankName: "Meezan Bank",
    logoPath: "/payment-method-logos/presets/meezan.svg",
    accountTitlePlaceholder: "Meezan account title",
    accountNumberLabel: "IBAN / Account Number",
    accountNumberPlaceholder: "PK00 MEZN 0000 1234 5678",
    instructionsHint: "Use for Meezan bank transfers and mention the exact beneficiary name.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "hbl",
    provider: "hbl",
    category: "Pakistan",
    label: "HBL",
    bankName: "HBL",
    logoPath: "/payment-method-logos/presets/hbl.svg",
    accountTitlePlaceholder: "HBL account title",
    accountNumberLabel: "IBAN / Account Number",
    accountNumberPlaceholder: "PK00 HABB 0000 1234 5678",
    instructionsHint: "Use for HBL transfers and specify the exact beneficiary details for players.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "bank_alfalah",
    provider: "bank_alfalah",
    category: "Pakistan",
    label: "Bank Alfalah",
    bankName: "Bank Alfalah",
    logoPath: "/payment-method-logos/presets/alfalah.svg",
    accountTitlePlaceholder: "Bank Alfalah account title",
    accountNumberLabel: "IBAN / Account Number",
    accountNumberPlaceholder: "PK00 ALFH 0000 1234 5678",
    instructionsHint: "Use for Bank Alfalah bank transfers with the beneficiary name and receipt requirement.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "sadapay",
    provider: "sadapay",
    category: "Pakistan",
    label: "SadaPay",
    bankName: "SadaPay",
    logoPath: "/payment-method-logos/presets/sadaPay.svg",
    accountTitlePlaceholder: "SadaPay account title",
    accountNumberLabel: "SadaPay Number",
    accountNumberPlaceholder: "03XX XXXXXXX",
    instructionsHint: "Use for SadaPay transfers and clearly mention proof or reference note requirements.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "mcb",
    provider: "mcb",
    category: "Pakistan",
    label: "MCB",
    bankName: "MCB",
    logoPath: "/payment-method-logos/presets/mcb.svg",
    accountTitlePlaceholder: "MCB account title",
    accountNumberLabel: "IBAN / Account Number",
    accountNumberPlaceholder: "PK00 MUCB 0000 1234 5678",
    instructionsHint: "Use for MCB transfers and clearly state the beneficiary name and receipt requirement.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "allied_bank",
    provider: "allied_bank",
    category: "Pakistan",
    label: "Allied Bank",
    bankName: "Allied Bank",
    logoPath: "/payment-method-logos/presets/allied-bank.svg",
    accountTitlePlaceholder: "Allied Bank account title",
    accountNumberLabel: "IBAN / Account Number",
    accountNumberPlaceholder: "PK00 ABLK 0000 1234 5678",
    instructionsHint: "Use for Allied Bank transfers with exact destination details and proof instructions.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "bank_of_punjab",
    provider: "bank_of_punjab",
    category: "Pakistan",
    label: "Bank of Punjab",
    bankName: "Bank of Punjab",
    logoPath: "/payment-method-logos/presets/bank-of-punjab.svg",
    accountTitlePlaceholder: "Bank of Punjab account title",
    accountNumberLabel: "IBAN / Account Number",
    accountNumberPlaceholder: "PK00 BPUN 0000 1234 5678",
    instructionsHint: "Use for Bank of Punjab transfers and mention any transfer note or receipt rule.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "paytm",
    provider: "paytm",
    category: "India",
    label: "Paytm",
    bankName: "Paytm",
    logoPath: "/payment-method-logos/presets/paytm.svg",
    accountTitlePlaceholder: "Paytm account title",
    accountNumberLabel: "Paytm Number",
    accountNumberPlaceholder: "+91 9XXXXXXXXX",
    instructionsHint: "Use for Paytm wallet transfers. Mention proof requirements and reference text.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "phonepe",
    provider: "phonepe",
    category: "India",
    label: "PhonePe",
    bankName: "PhonePe",
    logoPath: "/payment-method-logos/presets/phonepe.svg",
    accountTitlePlaceholder: "PhonePe account title",
    accountNumberLabel: "PhonePe Number / UPI",
    accountNumberPlaceholder: "name@upi",
    instructionsHint: "Use for PhonePe or linked UPI transfers.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "upi",
    provider: "upi",
    category: "India",
    label: "UPI",
    bankName: "UPI",
    logoPath: "/payment-method-logos/presets/upi.svg",
    accountTitlePlaceholder: "UPI payee name",
    accountNumberLabel: "UPI ID",
    accountNumberPlaceholder: "merchant@upi",
    instructionsHint: "Use for direct UPI transfers. Provide the exact UPI ID and payer note.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "google_pay_india",
    provider: "google_pay_india",
    category: "India",
    label: "Google Pay India",
    bankName: "Google Pay",
    logoPath: "/payment-method-logos/presets/google-pay-india.svg",
    accountTitlePlaceholder: "Google Pay payee name",
    accountNumberLabel: "UPI ID / Phone",
    accountNumberPlaceholder: "merchant@okaxis",
    instructionsHint: "Use for Google Pay India transfers with the exact UPI or linked phone number.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "skrill",
    provider: "skrill",
    category: "International",
    label: "Skrill",
    bankName: "Skrill",
    logoPath: "/payment-method-logos/presets/skrill.svg",
    accountTitlePlaceholder: "Skrill account holder",
    accountNumberLabel: "Skrill Email",
    accountNumberPlaceholder: "ops@example.com",
    instructionsHint: "Use for Skrill wallet transfers. Mention sender note or memo if needed.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "neteller",
    provider: "neteller",
    category: "International",
    label: "Neteller",
    bankName: "Neteller",
    logoPath: "/payment-method-logos/presets/neteller.svg",
    accountTitlePlaceholder: "Neteller account holder",
    accountNumberLabel: "Neteller ID / Email",
    accountNumberPlaceholder: "wallet@example.com",
    instructionsHint: "Use for Neteller wallet payouts or deposits with clear memo guidance.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "paypal",
    provider: "paypal",
    category: "International",
    label: "PayPal",
    bankName: "PayPal",
    logoPath: "/payment-method-logos/presets/paypal.svg",
    accountTitlePlaceholder: "PayPal account holder",
    accountNumberLabel: "PayPal Email",
    accountNumberPlaceholder: "ops@example.com",
    instructionsHint: "Use for PayPal transfers. Mention exactly which email to use and any note to include.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "apple_pay",
    provider: "apple_pay",
    category: "International",
    label: "Apple Pay",
    bankName: "Apple Pay",
    logoPath: "/payment-method-logos/presets/apple-pay.svg",
    accountTitlePlaceholder: "Apple Pay receiving name",
    accountNumberLabel: "Apple Pay Reference",
    accountNumberPlaceholder: "Linked number or payment request reference",
    instructionsHint: "Use for Apple Pay enabled transfers and explain the exact destination reference players should use.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "cash_app",
    provider: "cash_app",
    category: "International",
    label: "Cash App",
    bankName: "Cash App",
    logoPath: "/payment-method-logos/presets/cash-app.svg",
    accountTitlePlaceholder: "Cash App account holder",
    accountNumberLabel: "Cash Tag",
    accountNumberPlaceholder: "$yourcashtag",
    instructionsHint: "Use for Cash App transfers and provide the exact Cashtag for players.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "zelle",
    provider: "zelle",
    category: "International",
    label: "Zelle",
    bankName: "Zelle",
    logoPath: "/payment-method-logos/presets/zelle.svg",
    accountTitlePlaceholder: "Zelle account holder",
    accountNumberLabel: "Email / Phone",
    accountNumberPlaceholder: "zelle@example.com or +1 number",
    instructionsHint: "Use for Zelle transfers and provide the exact email or phone tied to the payout rail.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "usdt_trc20",
    provider: "usdt_trc20",
    category: "Crypto",
    label: "USDT TRC20",
    bankName: "TRON",
    logoPath: "/payment-method-logos/presets/usdt-trc20.svg",
    accountTitlePlaceholder: "Wallet owner name",
    accountNumberLabel: "Wallet Address",
    accountNumberPlaceholder: "TRxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    instructionsHint: "Tell the player to send only USDT on TRC20 and to upload the transfer hash or screenshot.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "usdt_erc20",
    provider: "usdt_erc20",
    category: "Crypto",
    label: "USDT ERC20",
    bankName: "Ethereum",
    logoPath: "/payment-method-logos/presets/usdt-erc20.svg",
    accountTitlePlaceholder: "Wallet owner name",
    accountNumberLabel: "Wallet Address",
    accountNumberPlaceholder: "0x1234567890abcdef1234567890abcdef12345678",
    instructionsHint: "Use only for ERC20 USDT and tell players to avoid sending funds on the wrong network.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "binance_pay",
    provider: "binance_pay",
    category: "Crypto",
    label: "Binance Pay",
    bankName: "Binance",
    logoPath: "/payment-method-logos/presets/binance-pay.svg",
    accountTitlePlaceholder: "Binance Pay account name",
    accountNumberLabel: "Binance Pay ID",
    accountNumberPlaceholder: "Binance Pay tag or QR reference",
    instructionsHint: "Use for Binance Pay transfers and specify the Binance Pay ID or note the player must use.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "usdt_bep20",
    provider: "usdt_bep20",
    category: "Crypto",
    label: "USDT BEP20",
    bankName: "BNB Smart Chain",
    logoPath: "/payment-method-logos/presets/usdt-bep20.svg",
    accountTitlePlaceholder: "Wallet owner name",
    accountNumberLabel: "Wallet Address",
    accountNumberPlaceholder: "0x1234567890abcdef1234567890abcdef12345678",
    instructionsHint: "Use only for BNB Smart Chain USDT and warn players not to send funds on the wrong network.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
  {
    key: "manual",
    provider: "manual",
    category: "Custom",
    label: "Custom Manual Method",
    bankName: "",
    logoPath: "/payment-method-logos/presets/manual.svg",
    accountTitlePlaceholder: "Destination title",
    accountNumberLabel: "Destination Reference",
    accountNumberPlaceholder: "Account number, tag, username, or wallet ID",
    instructionsHint: "Describe the manual steps clearly and state what the player must submit after sending funds.",
    defaultSupportsDeposit: true,
    defaultSupportsWithdrawal: true,
  },
];

export const PAYMENT_METHOD_PRESET_MAP = new Map(PAYMENT_METHOD_PRESETS.map((preset) => [preset.key, preset]));

export function resolvePaymentMethodLogoSrc(path?: string | null) {
  if (!path) return null;
  if (/^https?:\/\//.test(path)) return path;
  if (path.startsWith("/api/")) {
    const base = process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/+$/, "");
    if (base) return `${base}${path}`;
    if (typeof window !== "undefined") {
      return `${window.location.protocol}//${window.location.hostname}:4000${path}`;
    }
  }
  return path;
}
